apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-service 
  labels:
    app: cap-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cap-service 
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: cap-service  
    spec:     # pod spec                  
      containers: 
      - image: wiking/cap-test:latest # jcawley5/cap-service:latest # image we pushed
        name: cap-service  
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: cap-service 
  namespace: testcap
  labels:
    app: cap-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4004
    protocol: TCP
    targetPort: 4004
  selector:
    app: cap-service 
